### ISSUE TITLE
Fonts =/= Typefaces

### ISSUE THREAD

**Issue by stephenburgess8** [RoelN/Font-Falsehoods#1]
I think this idea is fantastic, kudos.

In my common speech, I've mostly abandoned using the term typeface outside of conversations with graphic designers, because most people don't know what it means. However since this is a place to talk about falsehoods relating to fonts, the equivocation of fonts and typefaces is up there for me.

When we say, "I used the Helvetica family" we're referring to the typeface, but when we say "I used Helvetica Light" we're talking about the font. Here's my attempt at being succinct about this:

`1. The terms font and typeface are completely interchangeable`

I actually have no problem with people using font to mean typeface. If I did, my head would have exploded a long time ago. But the word "font" didn't mean what it does now even 50 years ago. A common misunderstanding of the term due in large part to Microsoft Word has changed the common meaning of the word.

Cheers.

https://www.fastcodesign.com/3028971/whats-the-difference-between-a-font-and-a-typeface
http://nerdplusart.com/type-terminology-smackdown/

**Comment by kupfers** [comment]
I agree that there is generally a difference between font and typeface that is worth making, but in these cases, I understand that Roel is really talking about fonts – the digital file containing the manifestation of the typeface design. I just reread the list and didn’t find any violations of that idea. Can you point out what item specifically should say typeface instead of font?

(I’m referring to your comment in this tweet: https://twitter.com/uistephen/status/910146342286249985)

**Comment by stephenburgess8** [comment]
I'm afraid my original comment on Twitter came off a little strong. Since I've been thinking about this, I think it would be worthwhile to include something like my suggested text up above,

`1. The terms font and typeface are completely interchangeable`


`Everyone has the same fallback fonts installed` - when you declare fallbacks, you will do it by assigning a family name, so in that case I think there's an argument that you're declaring a fallback typeface rather than a font per se. But, I agree that changing it would be erring on the side of pedantry.

However I do think this document could be an excellent place to let people know that "typeface" and "font" used to have specific meanings which are not the same as the common usage. What better place to include that than in a list of falsehoods dev believe about fonts? The fact that the meaning of the word font has changed has to do with people being trained by using user interfaces and misinterpreting the label. User interface design changed the meaning of the word font.

Since it's more of a cultural historical fact, I could see why it would also not belong on this list from one point of view. So, if you think it's a good addition, add it, and if it doesn't fit your idea then don't. Anyway I've had fun thinking about this. 👍

**Comment by RoelN** [comment]
Added, thanks! :cake:
