### ISSUE TITLE
Styled font weights are as good as designed weights

### ISSUE THREAD

**Issue by stephenburgess8** [RoelN/Font-Falsehoods#2]
Starting in word processors, we gained the ability to apply styles like bold and italic to the regular weights of typefaces. However before this, those fonts were individually designed. An entire font would be cast for the italic weight, and for the bold. These were designed separately and individually balanced themselves.

However, starting with word-processors we gained the ability to apply a style, which transformed the normal weight of a typeface to be thicker for bold or slanted for italic. We can still do this in CSS when we only include the normal font of a typeface and apply `font-style` to it. So I think it's a common falsehood that applying a font style to a normal font-weight is just as good as including a separate font for that weight or style. I have seen people do this a lot.

`1. Styling a font is just as good as including the designed font for that style`

Having trouble making this one both succinct and clear, maybe you have a better phrasing.

**Comment by tigt** [comment]
The browser-specific term is [`font-synthesis`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis), maybe that would help convey?

**Comment by kupfers** [comment]
Stephen, are you explaining Roel his own falsehood list or do you just want to propose an edit in phrasing one item?

**Comment by kupfers** [comment]
Oops, disregard, I thought this item was already on the list. Good to point out.

**Comment by stephenburgess8** [comment]
TIL the term "font-synthesis".

Maybe

`1. Font-synthesis is just as good as a designed font style`

**Comment by RoelN** [comment]
"Bold or italics by font-synthesis is just as good as using actual bold or italic fonts"?

**Comment by Pomax** [comment]
I'd be even sillier than that. If you follow the "font" tag on Stackoverflow, the actual falsehood people believe is much stronger: "synthetic bold/italic look the same as using the 'real' bold/italic fonts"
