### ISSUE TITLE
Font weight/style/etc are automatically picked up by CSS

### ISSUE THREAD

**Issue by Pomax** [RoelN/Font-Falsehoods#4]
I've lost count of the number of times where the concept of "CSS will use whatever font you say it should use, specifically for the property values you add to your `@font-face` declaration" is one step beyond intuitive, leading to questions around "why isn't my font turning bold" etc.

**Comment by RoelN** [comment]
Thanks for submitting! I know what you're saying, how can we stuff this back in a short sentence?

**Comment by Pomax** [comment]
hmm... maybe "My one font contains all styles and weights"? It sounds silly when you phrase it like that, but a quick glance at Stackoverflow suggests this is a genuine assumption by people who "just want to use a webfont".
