### ISSUE TITLE
to add to 19/20: you're allowed to host any font

### ISSUE THREAD

**Issue by Pomax** [RoelN/Font-Falsehoods#5]
"it came with my OS, everyone has it, I'm just hosting it to make sure we're all using the same version". Cool story, except you got it with your OS or bundled with very specific software, the family costs $799 on its own, and the license is pretty explicit in that you have zero distribution rights =)

(this could also be a 'version b' of "all fonts are free" - "the fonts that come with your OS are free")

**Comment by RoelN** [comment]
Thanks, added "The fonts that came with my OS can be freely uploaded to my server". I hope that covers it well enough!
